'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Eligibility

    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_mv1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _mv1 As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''_v_eligibility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _v_eligibility As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''_div_hdr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _div_hdr As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_pnl_provider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _pnl_provider As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''providerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents providerName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''providerName_AutoCompleteExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents providerName_AutoCompleteExtender As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''_hf_provider_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _hf_provider_id As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''_tbCardNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _tbCardNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_tbreferral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _tbreferral As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''_v_detail_member control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _v_detail_member As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''_lbl_header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_header As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridMemberDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMemberDetail As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_pnl_member_benefit_vm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _pnl_member_benefit_vm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gridExtraBenefit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridExtraBenefit As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_pnl_member_benefit_ib control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _pnl_member_benefit_ib As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gridLimitBenefit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridLimitBenefit As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_pnl_member_benefit_cob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _pnl_member_benefit_cob As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gridLimitBenefitCOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridLimitBenefitCOB As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_ddl_service control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _ddl_service As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''_req_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _req_1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''_btn_registrasi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _btn_registrasi As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''_v_success control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _v_success As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''_lbl_header_success control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_header_success As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_lbl_result_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_result_text As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_tbl_result control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _tbl_result As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''_lbl_success_hdr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_success_hdr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_lbl_suc_transaction_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_suc_transaction_id As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_lbl_suc_card_no control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_suc_card_no As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_lbl_suc_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_suc_name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_lbl_suc_payor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_suc_payor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_lbl_suc_client control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_suc_client As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_lbl_suc_benefit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_suc_benefit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_lbl_admisson_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_admisson_date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_lbl_process_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_process_date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_lbl_referral_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_referral_code As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_pnl_btn_registration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _pnl_btn_registration As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_btn_registration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _btn_registration As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''_pnl_btn_fkc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _pnl_btn_fkc As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_btn_fkc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _btn_fkc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''_pnl_btn_fim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _pnl_btn_fim As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_btn_fim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _btn_fim As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''_pnl_btn_surat_pernyataan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _pnl_btn_surat_pernyataan As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_btn_surat_pernyataan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _btn_surat_pernyataan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''v_error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_error As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''_lbl_error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_error As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_lbl_popup_header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_popup_header As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gv_benefit_detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_benefit_detail As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''LinkButton2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButton2 As Global.System.Web.UI.WebControls.LinkButton
End Class
