'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TambahProvider

    '''<summary>
    '''_lbl_header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_header As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''providerid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents providerid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtnama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnama As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAlamat1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlamat1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAlamat2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlamat2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAlamat3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlamat3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtZipcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtZipcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtphone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtphone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtphone2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtphone2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtfax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtfax2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfax2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtemail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtemail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_btnsimpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _btnsimpan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cancel As Global.System.Web.UI.WebControls.Button
End Class
