'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("dsRptSuratPernyataan"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class dsRptSuratPernyataan
    Inherits Global.System.Data.DataSet
    
    Private tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC")) Is Nothing) Then
                MyBase.Tables.Add(New USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCDataTable(ds.Tables("USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC() As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCDataTable
        Get
            Return Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As dsRptSuratPernyataan = CType(MyBase.Clone,dsRptSuratPernyataan)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXml(reader)
            If (Not (ds.Tables("USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC")) Is Nothing) Then
                MyBase.Tables.Add(New USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCDataTable(ds.Tables("USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC = CType(MyBase.Tables("USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC"),USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCDataTable)
        If (initTable = true) Then
            If (Not (Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC) Is Nothing) Then
                Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub InitClass()
        Me.DataSetName = "dsRptSuratPernyataan"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/dsRptSuratPernyataan.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC = New USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCDataTable()
        MyBase.Tables.Add(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Function ShouldSerializeUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As dsRptSuratPernyataan = New dsRptSuratPernyataan()
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Delegate Sub USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowChangeEventHandler(ByVal sender As Object, ByVal e As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCDataTable
        Inherits Global.System.Data.TypedTableBase(Of USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow)
        
        Private columnTRANSACTIONID As Global.System.Data.DataColumn
        
        Private columnCARDNO As Global.System.Data.DataColumn
        
        Private columnPATIENT As Global.System.Data.DataColumn
        
        Private columnEMPLOYEE As Global.System.Data.DataColumn
        
        Private columnCLIENTNM As Global.System.Data.DataColumn
        
        Private columnPAYORNM As Global.System.Data.DataColumn
        
        Private columnREFERRALCODE As Global.System.Data.DataColumn
        
        Private columnADMISSIONDT As Global.System.Data.DataColumn
        
        Private columnPROVIDERNAME As Global.System.Data.DataColumn
        
        Private columnBUILDING As Global.System.Data.DataColumn
        
        Private columnSTREET1 As Global.System.Data.DataColumn
        
        Private columnPHONE1 As Global.System.Data.DataColumn
        
        Private columnFAX1 As Global.System.Data.DataColumn
        
        Private columnPOLICYNO As Global.System.Data.DataColumn
        
        Private columnBIRTHDATE As Global.System.Data.DataColumn
        
        Private columnSEXNM2 As Global.System.Data.DataColumn
        
        Private columnSERVICENM As Global.System.Data.DataColumn
        
        Private columnEFFDT As Global.System.Data.DataColumn
        
        Private columnEXPDT As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property TRANSACTIONIDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTRANSACTIONID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CARDNOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCARDNO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PATIENTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPATIENT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property EMPLOYEEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEMPLOYEE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CLIENTNMColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCLIENTNM
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PAYORNMColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPAYORNM
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property REFERRALCODEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnREFERRALCODE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ADMISSIONDTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnADMISSIONDT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PROVIDERNAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPROVIDERNAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property BUILDINGColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnBUILDING
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property STREET1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnSTREET1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PHONE1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnPHONE1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property FAX1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnFAX1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property POLICYNOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPOLICYNO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property BIRTHDATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnBIRTHDATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property SEXNM2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnSEXNM2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property SERVICENMColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSERVICENM
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property EFFDTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEFFDT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property EXPDTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEXPDT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow
            Get
                Return CType(Me.Rows(index),USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowChanging As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowChanged As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowDeleting As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowDeleted As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Sub AddUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow(ByVal row As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Function AddUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow( _
                    ByVal TRANSACTIONID As String,  _
                    ByVal CARDNO As String,  _
                    ByVal PATIENT As String,  _
                    ByVal EMPLOYEE As String,  _
                    ByVal CLIENTNM As String,  _
                    ByVal PAYORNM As String,  _
                    ByVal REFERRALCODE As String,  _
                    ByVal ADMISSIONDT As Date,  _
                    ByVal PROVIDERNAME As String,  _
                    ByVal BUILDING As String,  _
                    ByVal STREET1 As String,  _
                    ByVal PHONE1 As String,  _
                    ByVal FAX1 As String,  _
                    ByVal POLICYNO As String,  _
                    ByVal BIRTHDATE As Date,  _
                    ByVal SEXNM2 As String,  _
                    ByVal SERVICENM As String,  _
                    ByVal EFFDT As String,  _
                    ByVal EXPDT As String) As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow
            Dim rowUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow = CType(Me.NewRow,USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow)
            Dim columnValuesArray() As Object = New Object() {TRANSACTIONID, CARDNO, PATIENT, EMPLOYEE, CLIENTNM, PAYORNM, REFERRALCODE, ADMISSIONDT, PROVIDERNAME, BUILDING, STREET1, PHONE1, FAX1, POLICYNO, BIRTHDATE, SEXNM2, SERVICENM, EFFDT, EXPDT}
            rowUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow)
            Return rowUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCDataTable = CType(MyBase.Clone,USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCDataTable()
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub InitVars()
            Me.columnTRANSACTIONID = MyBase.Columns("TRANSACTIONID")
            Me.columnCARDNO = MyBase.Columns("CARDNO")
            Me.columnPATIENT = MyBase.Columns("PATIENT")
            Me.columnEMPLOYEE = MyBase.Columns("EMPLOYEE")
            Me.columnCLIENTNM = MyBase.Columns("CLIENTNM")
            Me.columnPAYORNM = MyBase.Columns("PAYORNM")
            Me.columnREFERRALCODE = MyBase.Columns("REFERRALCODE")
            Me.columnADMISSIONDT = MyBase.Columns("ADMISSIONDT")
            Me.columnPROVIDERNAME = MyBase.Columns("PROVIDERNAME")
            Me.columnBUILDING = MyBase.Columns("BUILDING")
            Me.columnSTREET1 = MyBase.Columns("STREET1")
            Me.columnPHONE1 = MyBase.Columns("PHONE1")
            Me.columnFAX1 = MyBase.Columns("FAX1")
            Me.columnPOLICYNO = MyBase.Columns("POLICYNO")
            Me.columnBIRTHDATE = MyBase.Columns("BIRTHDATE")
            Me.columnSEXNM2 = MyBase.Columns("SEXNM2")
            Me.columnSERVICENM = MyBase.Columns("SERVICENM")
            Me.columnEFFDT = MyBase.Columns("EFFDT")
            Me.columnEXPDT = MyBase.Columns("EXPDT")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Private Sub InitClass()
            Me.columnTRANSACTIONID = New Global.System.Data.DataColumn("TRANSACTIONID", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTRANSACTIONID)
            Me.columnCARDNO = New Global.System.Data.DataColumn("CARDNO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCARDNO)
            Me.columnPATIENT = New Global.System.Data.DataColumn("PATIENT", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPATIENT)
            Me.columnEMPLOYEE = New Global.System.Data.DataColumn("EMPLOYEE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEMPLOYEE)
            Me.columnCLIENTNM = New Global.System.Data.DataColumn("CLIENTNM", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCLIENTNM)
            Me.columnPAYORNM = New Global.System.Data.DataColumn("PAYORNM", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPAYORNM)
            Me.columnREFERRALCODE = New Global.System.Data.DataColumn("REFERRALCODE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnREFERRALCODE)
            Me.columnADMISSIONDT = New Global.System.Data.DataColumn("ADMISSIONDT", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnADMISSIONDT)
            Me.columnPROVIDERNAME = New Global.System.Data.DataColumn("PROVIDERNAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPROVIDERNAME)
            Me.columnBUILDING = New Global.System.Data.DataColumn("BUILDING", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBUILDING)
            Me.columnSTREET1 = New Global.System.Data.DataColumn("STREET1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSTREET1)
            Me.columnPHONE1 = New Global.System.Data.DataColumn("PHONE1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPHONE1)
            Me.columnFAX1 = New Global.System.Data.DataColumn("FAX1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnFAX1)
            Me.columnPOLICYNO = New Global.System.Data.DataColumn("POLICYNO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPOLICYNO)
            Me.columnBIRTHDATE = New Global.System.Data.DataColumn("BIRTHDATE", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBIRTHDATE)
            Me.columnSEXNM2 = New Global.System.Data.DataColumn("SEXNM2", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSEXNM2)
            Me.columnSERVICENM = New Global.System.Data.DataColumn("SERVICENM", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSERVICENM)
            Me.columnEFFDT = New Global.System.Data.DataColumn("EFFDT", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEFFDT)
            Me.columnEXPDT = New Global.System.Data.DataColumn("EXPDT", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEXPDT)
            Me.columnTRANSACTIONID.AllowDBNull = false
            Me.columnTRANSACTIONID.MaxLength = 50
            Me.columnCARDNO.MaxLength = 50
            Me.columnPATIENT.MaxLength = 150
            Me.columnEMPLOYEE.MaxLength = 50
            Me.columnCLIENTNM.MaxLength = 300
            Me.columnPAYORNM.MaxLength = 300
            Me.columnREFERRALCODE.MaxLength = 50
            Me.columnPROVIDERNAME.MaxLength = 100
            Me.columnBUILDING.MaxLength = 50
            Me.columnSTREET1.MaxLength = 50
            Me.columnPHONE1.MaxLength = 15
            Me.columnFAX1.MaxLength = 15
            Me.columnPOLICYNO.AllowDBNull = false
            Me.columnPOLICYNO.MaxLength = 30
            Me.columnSEXNM2.MaxLength = 10
            Me.columnSERVICENM.MaxLength = 50
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function NewUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow() As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow
            Return CType(Me.NewRow,USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowChangedEvent) Is Nothing) Then
                RaiseEvent USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowChanged(Me, New USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowChangeEvent(CType(e.Row,USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowChangingEvent) Is Nothing) Then
                RaiseEvent USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowChanging(Me, New USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowChangeEvent(CType(e.Row,USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowDeletedEvent) Is Nothing) Then
                RaiseEvent USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowDeleted(Me, New USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowChangeEvent(CType(e.Row,USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowDeletingEvent) Is Nothing) Then
                RaiseEvent USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowDeleting(Me, New USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowChangeEvent(CType(e.Row,USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub RemoveUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow(ByVal row As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
            Dim ds As dsRptSuratPernyataan = New dsRptSuratPernyataan()
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    Partial Public Class USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow
        Inherits Global.System.Data.DataRow
        
        Private tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC = CType(Me.Table,USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property TRANSACTIONID() As String
            Get
                Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.TRANSACTIONIDColumn),String)
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.TRANSACTIONIDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CARDNO() As String
            Get
                Try 
                    Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.CARDNOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CARDNO' in table 'USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC' is DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.CARDNOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PATIENT() As String
            Get
                Try 
                    Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.PATIENTColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PATIENT' in table 'USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC' is DBN"& _ 
                            "ull.", e)
                End Try
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.PATIENTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property EMPLOYEE() As String
            Get
                Try 
                    Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.EMPLOYEEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'EMPLOYEE' in table 'USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC' is DB"& _ 
                            "Null.", e)
                End Try
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.EMPLOYEEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CLIENTNM() As String
            Get
                Try 
                    Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.CLIENTNMColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CLIENTNM' in table 'USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC' is DB"& _ 
                            "Null.", e)
                End Try
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.CLIENTNMColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PAYORNM() As String
            Get
                Try 
                    Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.PAYORNMColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PAYORNM' in table 'USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC' is DBN"& _ 
                            "ull.", e)
                End Try
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.PAYORNMColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property REFERRALCODE() As String
            Get
                Try 
                    Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.REFERRALCODEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'REFERRALCODE' in table 'USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC' i"& _ 
                            "s DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.REFERRALCODEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ADMISSIONDT() As Date
            Get
                Try 
                    Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.ADMISSIONDTColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ADMISSIONDT' in table 'USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC' is"& _ 
                            " DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.ADMISSIONDTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PROVIDERNAME() As String
            Get
                Try 
                    Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.PROVIDERNAMEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PROVIDERNAME' in table 'USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC' i"& _ 
                            "s DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.PROVIDERNAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property BUILDING() As String
            Get
                Try 
                    Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.BUILDINGColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'BUILDING' in table 'USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC' is DB"& _ 
                            "Null.", e)
                End Try
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.BUILDINGColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property STREET1() As String
            Get
                Try 
                    Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.STREET1Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'STREET1' in table 'USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC' is DBN"& _ 
                            "ull.", e)
                End Try
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.STREET1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PHONE1() As String
            Get
                Try 
                    Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.PHONE1Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PHONE1' in table 'USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC' is DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.PHONE1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property FAX1() As String
            Get
                Try 
                    Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.FAX1Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'FAX1' in table 'USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC' is DBNull"& _ 
                            ".", e)
                End Try
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.FAX1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property POLICYNO() As String
            Get
                Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.POLICYNOColumn),String)
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.POLICYNOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property BIRTHDATE() As Date
            Get
                Try 
                    Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.BIRTHDATEColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'BIRTHDATE' in table 'USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC' is D"& _ 
                            "BNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.BIRTHDATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property SEXNM2() As String
            Get
                Try 
                    Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.SEXNM2Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SEXNM2' in table 'USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC' is DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.SEXNM2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property SERVICENM() As String
            Get
                Try 
                    Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.SERVICENMColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SERVICENM' in table 'USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC' is D"& _ 
                            "BNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.SERVICENMColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property EFFDT() As String
            Get
                Try 
                    Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.EFFDTColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'EFFDT' in table 'USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC' is DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.EFFDTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property EXPDT() As String
            Get
                Try 
                    Return CType(Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.EXPDTColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'EXPDT' in table 'USP_RPT_REKAM_MEDIS_ISOMEDIK_FKC' is DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.EXPDTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsCARDNONull() As Boolean
            Return Me.IsNull(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.CARDNOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetCARDNONull()
            Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.CARDNOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsPATIENTNull() As Boolean
            Return Me.IsNull(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.PATIENTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetPATIENTNull()
            Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.PATIENTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsEMPLOYEENull() As Boolean
            Return Me.IsNull(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.EMPLOYEEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetEMPLOYEENull()
            Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.EMPLOYEEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsCLIENTNMNull() As Boolean
            Return Me.IsNull(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.CLIENTNMColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetCLIENTNMNull()
            Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.CLIENTNMColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsPAYORNMNull() As Boolean
            Return Me.IsNull(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.PAYORNMColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetPAYORNMNull()
            Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.PAYORNMColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsREFERRALCODENull() As Boolean
            Return Me.IsNull(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.REFERRALCODEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetREFERRALCODENull()
            Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.REFERRALCODEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsADMISSIONDTNull() As Boolean
            Return Me.IsNull(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.ADMISSIONDTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetADMISSIONDTNull()
            Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.ADMISSIONDTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsPROVIDERNAMENull() As Boolean
            Return Me.IsNull(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.PROVIDERNAMEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetPROVIDERNAMENull()
            Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.PROVIDERNAMEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsBUILDINGNull() As Boolean
            Return Me.IsNull(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.BUILDINGColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetBUILDINGNull()
            Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.BUILDINGColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsSTREET1Null() As Boolean
            Return Me.IsNull(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.STREET1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetSTREET1Null()
            Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.STREET1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsPHONE1Null() As Boolean
            Return Me.IsNull(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.PHONE1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetPHONE1Null()
            Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.PHONE1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsFAX1Null() As Boolean
            Return Me.IsNull(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.FAX1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetFAX1Null()
            Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.FAX1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsBIRTHDATENull() As Boolean
            Return Me.IsNull(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.BIRTHDATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetBIRTHDATENull()
            Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.BIRTHDATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsSEXNM2Null() As Boolean
            Return Me.IsNull(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.SEXNM2Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetSEXNM2Null()
            Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.SEXNM2Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsSERVICENMNull() As Boolean
            Return Me.IsNull(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.SERVICENMColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetSERVICENMNull()
            Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.SERVICENMColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsEFFDTNull() As Boolean
            Return Me.IsNull(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.EFFDTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetEFFDTNull()
            Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.EFFDTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsEXPDTNull() As Boolean
            Return Me.IsNull(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.EXPDTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetEXPDTNull()
            Me(Me.tableUSP_RPT_REKAM_MEDIS_ISOMEDIK_FKC.EXPDTColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Class USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New(ByVal row As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Row() As USP_RPT_REKAM_MEDIS_ISOMEDIK_FKCRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
